name: Type check and lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  typecheck-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: bun install

      - name: Type check and lint
        run: bun run typecheck && bun run lint
        env:
          # use dummy env variables to bypass t3-env check
          DATABASE_URL: mysql://test:xxxx@xxxxxxxxx:3306/test
          SMTP_HOST: host
          SMTP_PORT: 587
          SMTP_USER: user
          SMTP_PASSWORD: password
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          ALLOW_SIGNIN_SIGNUP: true
          GITHUB_CLIENT_ID: client_id
          GITHUB_CLIENT_SECRET: client_secret
          STRIPE_API_KEY: stripe_api_key
          STRIPE_WEBHOOK_SECRET: stripe_webhook_secret
          STRIPE_PRO_MONTHLY_PLAN_ID: stripe_pro_monthly_plan_id
